import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";

import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import {Header} from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
      <Header/>
          <main className="px-20 m-auto">{children}</main>
      </body>
      <Toaster />
    </html>
  );
}
